### ISSUE TITLE
As cluer, I want to see the choices in context

### ISSUE THREAD

**Issue by augustoroman** [sillypantscoder/huesandcues#2]
Sometimes I'll think of the colors differently depending on where they are vs seeing the color block by itself.

In fact, some colors only make sense in context: https://www.youtube.com/watch?v=wh4aWZRtTwU

**Comment by sillypantscoder** [comment]
[Fixed](https://github.com/sillypantscoder/huesandcues/commit/5f8a211cde2024c5e3debebf5a2112dc696f0508)
